language: java
jdk:
  - openjdk8

# execute option when only committing master branch
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - qkqk9898@naver.com
      
script:
  "mvn test -B"